---
- name: disable swap
  systemd:
    name: dphys-swapfile
    state: stopped
    enabled: no

- name: enable cgroup memory
  lineinfile:
     path: /boot/cmdline.txt
     regexp: '^(.*)fsck.repair=yes rootwait(.*)$'
     line: '\1fsck.repair=yes cgroup_enable=memory rootwait\2'
     backrefs: yes

- name: install google packages apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: add kubernetes repo
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    #repo: deb http://apt.kubernetes.io/ kubernetes-{{ ansible_distribution_release }} main

- name: install kubernetes packages
  apt:
    name: "{{ item }}"
    force: yes
    state: present
    update_cache: yes
  with_items:
    - kubelet={{ kubernetes.version }}
    - kubeadm={{ kubernetes.version }}
    - kubectl={{ kubernetes.version }}
    - kubernetes-cni
