---
- name: kubeadm | Reset if requested
  command: kubeadm reset
  when: kubernetes_reset
  tags:
    - reset

- name: kubeadm | Check for a running cluster
  command: kubectl get nodes
  register: _kubectl_result
  failed_when: _kubectl_result.rc == 2
  changed_when: _kubectl_result.rc == 1

- block:

  - name: kubeadm | Setup master
    include_tasks: master.yml
    when: kubernetes_mode == "master"

  - name: kubeadm | Setup node
    include_tasks: node.yml
    when: kubernetes_mode == "node"

  when: _kubectl_result.rc == 1 or kubernetes_reset
