---
- name: kubeadm-node | Register token as fact
  set_fact:
    kubeadm_token: "{{ lookup('file', playbook_dir + '/run/kubeadm-token.txt') }}"

- name: kubeadm-node | check if cluster is already configured
  stat:
    path: /var/lib/kubelet/config.yaml
  register: _kubernetes_stat_kubelet_config

- name: kubeadm-node | Clean up /var/lib/kubelet/
  file:
    path: /var/lib/kubelet/pki
    state: absent
  when: not _kubernetes_stat_kubelet_config.stat.exists

- name: kubeadm-node | Run kubeadm join on node
  command: kubeadm join --token={{ kubeadm_token }} --discovery-token-unsafe-skip-ca-verification {{ kubernetes_master_ip }}:6443
  when: not _kubernetes_stat_kubelet_config.stat.exists

- name: kubeadm-node | Wait for /etc/kubernetes/kubelet.conf to be created
  wait_for:
    path: /etc/kubernetes/kubelet.conf

- name: kubeadm-node | Copy Kubernetes access config to ~/.kube/config on nodes
  copy:
    remote_src: True
    src: /etc/kubernetes/kubelet.conf
    dest: /home/{{ kubernetes_user }}/.kube/config
    owner: "{{ kubernetes_user }}"
    group: users

#- name: kubeadm-node | Fix permission for kubelet-client.key
#  file:
#    path: /var/lib/kubelet/pki/kubelet-client.key
#    mode: "660"
#    group: users

#- name: kubeadm-node | Fix permission for kubelet.key
#  file:
#    path: /var/lib/kubelet/pki/kubelet.key
#    mode: "660"
#    group: users
